require:
    - rubocop-rails

AllCops:
    TargetRubyVersion: 2.5
    Exclude:
        - 'db/migrate/**/*'
        - 'db/data_migrate/**/*'
        - 'db/schema.rb'
        - 'db/seeds.rb'
        - 'bin/**/*'
        - 'tmp/**/*'
        - 'vendor/**/*'
        - 'lib/**/*'
        - 'config/puma.rb'

Rails:
    Enabled: true

Bundler/OrderedGems:
    Enabled: false

Rails/Output:
    Exclude:
        - 'db/data_migrate/**/*'
        - 'lib/fdl/validations/**/*'

Rails/FilePath:
    Enabled: false

Rails/UniqueValidationWithoutIndex:
    Enabled: false

Rails/ApplicationController:
    Enabled: false

Style/GlobalStdStream:
    Exclude:
        - 'config/environments/production.rb'

Style/ExponentialNotation:
    Enabled: false

Style/GuardClause:
    Exclude:
    - 'app/models/framework/definition/ast/field/options.rb'
    - 'app/models/framework/definition/ast/semantic_checker.rb'

Style/AndOr:
    Enabled: false

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Style/ClassCheck:
    Enabled: false

Layout/HashAlignment:
    Enabled: false

Layout/TrailingEmptyLines:
    Enabled: true

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50
    Exclude:

Metrics/AbcSize:
    Max: 21
    Exclude:
        - 'spec/**/*'
        - 'lib/console_helpers.rb'
        - 'app/models/submission_completion.rb'
        - 'app/controllers/admin/suppliers_controller.rb'

Layout/LineLength:
    Max: 120
    Exclude:
        - 'app/models/framework/definition/**/*'
        - 'app/models/task/unfinished_user_notification_list.rb'
        - 'app/models/workday/commercial_agreements.rb'

Metrics/BlockLength:
    Max: 40
    Exclude:
        - 'spec/**/*'
        - 'config/routes.rb'

Naming/ClassAndModuleCamelCase:
    Exclude:
        - 'app/models/framework/definition/**/*'

Naming/FileName:
    Exclude:
        - 'app/models/framework/definition/**/*'
        - 'spec/models/framework/definition/RM1070_spec.rb'

Naming/VariableNumber:
    Exclude:
        - 'spec/**/*'

Lint/AmbiguousBlockAssociation:
    Exclude:
        - 'spec/**/*'

Lint/MissingSuper:
    Enabled: false

Style/MultilineBlockChain:
    Exclude:
        - 'app/models/framework/definition/transpiler.rb'

Naming/MemoizedInstanceVariableName:
    Exclude:
        - 'app/models/framework/definition/transpiler.rb'

Lint/UnderscorePrefixedVariableName:
    Exclude:
        - 'app/models/framework/definition/transpiler.rb'

Metrics/CyclomaticComplexity:
    Exclude:
        - 'app/models/framework/definition/ast/field.rb'
        - 'app/models/framework/definition/ast/semantic_checker.rb'
        - 'app/models/ingest/loader.rb'

Metrics/PerceivedComplexity:
    Exclude:
        - 'app/models/framework/definition/ast/field.rb'
