language: ruby
rvm:
- 2.6.7
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    update: true
    packages:
      - postgresql-10
      - postgresql-client-10
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel
dist: xenial
cache:
  - bundler
  - pip
env:
  matrix:
    - API_ROOT='https://ccs.api/'
  global:
    - CF_ORG=ccs-report-management-info
    - secure: "N9v+XZcjaaF1nkd+/vim5P3ssK/l9pbQQ5ihliIIkMmXQlURP11xovXxAy0pkqFQC+Vi97f9nYTB+9rWg0KeoSaSpi7F0od8/UASSg9z7TkfxIY4MeqQgPGczwpuKmw3IF5/Qduw9bMFR3tqQsJAwN9rqpKIvo7/TS9sgiNLu9cV1WDDOYE0ItkgyjWkiGtXace98eUaRq3Zpu8i5a8FvpyP1wn2jZDD7ST9I5EFJUXS+18VGHFVdNoGWY3pfPm9+HCLyIkvKc3PMEAv6u95hBoLJVeuI29PH4Lv/q8PVSkNZ8L5whWXVVA9JIhOzBZwjBgd8s7GODAaPhDN6HTt7K1HtU04U6M1L+LvDCOZGM1eoIThgCUP60Y8h5aw6ECJENMrwt4WymJQ07svvGmg9vIuE8864hQC34+lpa0mDreEk2E5rJS/P2o/XlhwMIDvOySNGixd5hjydINxgFfP8/6yhaDJ8Q4lsbPuQsSU0HW8dXNiVRXCTBt2T31mUPNwEA/VeBHa5zMu8IEdV17s0GyNJIWtx0HebXPI7jVBDyhkuhsIlptAasWVHSOoA0YjNW/0aJa2HOW/ad1kOEs14RpbooM1UJsF8GQwMAdUe6nnt/FPen+ZErrFEaiMnpyLOyZnSn8FKBmTsVKz+Zoc+Su/fHEu5L0btVXUGeg/BbA="
before_install:
  - gem install bundler -v 2.0.2
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64  > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - bundle install --jobs=3 --retry=3 --deployment --without=production --path=${BUNDLE_PATH:-vendor/bundle}
  # - pip3 install --upgrade pip
  - pyenv global 3.7.1
  - pip3 install --user --upgrade -r $PWD/requirements.txt --no-cache-dir
before_script:
  - ./cc-test-reporter before-build
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake AWS_ACCESS_KEY_ID=dummy AWS_SECRET_ACCESS_KEY=dummy AWS_S3_REGION=dummy AWS_S3_BUCKET=dummy SECRET_KEY_BASE=dummy DATABASE_URL=postgresql:does_not_exist --quiet assets:precompile
bundler_args: --without production
before_deploy:
  - echo "install cloudfoundry cli"
  - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  - echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
  - sudo apt-get update -qq
  - sudo apt-get install cf7-cli
deploy:
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s staging
    on:
      branch: develop
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s preprod
    on:
      branch: conclave
  - provider: script
    script: bash CF/deploy-app.sh -u $CF_USER -o $CF_ORG -p $CF_PASS -s prod
    on:
      branch: master
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
