language: ruby
rvm:
- 2.5.5
services:
  - postgresql
addons:
  postgresql: "10"
apt:
  packages:
  - postgresql-10
  - postgresql-client-10
dist: xenial
cache:
  - bundler
env:
  - API_ROOT='https://ccs.api/' AWS_S3_REGION='eu-west-2'
before_script:
  - bundle exec bin/rails db:migrate RAILS_ENV=test
  - bundle exec rake AWS_ACCESS_KEY_ID=dummy AWS_SECRET_ACCESS_KEY=dummy AWS_S3_REGION=dummy AWS_S3_BUCKET=dummy SECRET_KEY_BASE=dummy DATABASE_URL=postgresql:does_not_exist --quiet assets:precompile
