language: ruby
rvm:
- 2.5.5
services:
  - postgresql
addons:
  postgresql: "10"
apt:
  update: true
  packages:
  - postgresql-10
  - postgresql-client-10
  - python3
  - python3-pip
  - python3-setuptools
  - python3-wheel
dist: xenial
cache:
  - bundler
  - pip
env:
  - API_ROOT='https://ccs.api/' AWS_S3_REGION='eu-west-2'
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install --jobs=3 --retry=3 --deployment --without=production --path=${BUNDLE_PATH:-vendor/bundle}
  - pyenv global 3.7.1
  - pip3 install --user --upgrade -r $PWD/requirements.txt
before_script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rake AWS_ACCESS_KEY_ID=dummy AWS_SECRET_ACCESS_KEY=dummy AWS_S3_REGION=dummy AWS_S3_BUCKET=dummy SECRET_KEY_BASE=dummy DATABASE_URL=postgresql:does_not_exist --quiet assets:precompile
bundler_args: --without production
