---
version: '3'
services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: "development"
    image: local/data_submission_service_api_app
    ports: ["3000:3000"]
    environment:
      RAILS_ENV: "development"
    env_file:
      - docker-compose.env
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - .:/srv/dss-api:cached
    command: bash -c "rm -f tmp/pids/server.pid && rails s"
    container_name: "data-submission-service-api_web"
    networks:
      public:
        aliases:
          - api
      private:
  worker:
    image: local/data_submission_service_api_app
    build:
      context: .
      args:
        RAILS_ENV: "development"
    environment:
      RAILS_ENV: "development"
    env_file:
      - docker-compose.env
    depends_on:
      - db
      - redis
      - web
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - .:/srv/dss-api:cached
    command: bash -c "bundle exec sidekiq"
    container_name: "data-submission-service-api_worker"
    networks:
      private:
  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/:cached
    restart: on-failure
    container_name: "data-submission-service-api_db"
    networks:
      private:
  redis:
    image: redis
    container_name: "data-submission-service-api_redis"
    expose:
      - 6379
    networks:
      private:

volumes:
  pg_data: {}

networks:
  public:
  private:
