---
version: '3'
services:
  test: &test
    build:
      context: .
      args:
        RAILS_ENV: "test"
    environment:
      RAILS_ENV: "test"
      DATABASE_URL: "postgres://postgres@db-test:5432/DataSubmissionServiceApi_test?template=template0&pool=5&encoding=unicode"
      AWS_S3_REGION: 'eu-west-2'
    env_file:
      - docker-compose.env
    volumes:
      - .:/srv/dss-api:cached
    depends_on:
      - db-test
    command: ["bundle", "exec", "./bin/dsetup && spring server"]
    restart: on-failure
    networks:
      - tests
    container_name: data-submission-service-api_test

  db-test:
    image: postgres
    volumes:
      - pg_test_data:/var/lib/postgresql/data/:cached
    networks:
      - tests
    restart: on-failure
    container_name: data-submission-service-api_db-test

networks:
  tests:

volumes:
  pg_test_data: {}
