---
version: '3'
services:
  web:
    build:
      context: .
      args:
        RAILS_ENV: "development"
    ports: ["3000:3000"]
    environment:
      RAILS_ENV: "development"
    env_file:
      - docker-compose.env
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
    restart: on-failure
    volumes:
      - .:/srv/dss-api:cached
    command: bash -c "rm -f tmp/pids/server.pid && rails s"
    container_name: "data-submission-service-api_web"

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/:cached
    restart: on-failure
    container_name: "data-submission-service-api_db"
  redis:
    image: redis
    expose:
    - 6379
volumes:
  pg_data: {}
