---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  generateName: buildkit-
  labels:
    app.kubernetes.io/name: data-submission-service-api
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 40Gi
  storageClassName: fast-disks
