monthly_tasks_generation:
  cron: '0 2 1 * *'
  class: 'MonthlyTasksGenerationJob'
  queue: default
daily_data_warehouse_export:
  cron: '30 22 * * * Europe/London'
  class: DataWarehouseExportJob
  queue: default
