name: RMI Backend CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: data_submission_service_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:@localhost:5432/data_submission_service_test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Set up database.yml
        run: cp config/database.travis.yml config/database.yml

      - name: Create test database
        run: |
          sudo apt-get install -y postgresql-client
          psql -c 'create database data_submission_service_test;' -U postgres

      - name: Run migrations
        run: bundle exec rails db:migrate

      - name: Run tests
        run: bundle exec rspec