name: RMI Backend CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: data_submission_service_api_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/data_submission_service_api_test

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true
        env: 
          BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
        env: 
          BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}

      # - name: Wait for Postgres to be ready
      #   run: |
      #     until pg_isready -h postgres -p 5432 -U postgres; do
      #       echo "Waiting for Postgres..."
      #       sleep 2
      #     done
      #   env:
      #     PGPASSWORD: postgres

      # - name: Create test database
      #   run: |
      #     bundle exec rails db:create
      #     bundle exec rails db:schema:load

      - name: Run migrations
        run: bundle exec rails db:migrate

      - name: Compile assets
        run: bin/rails assets:precompile

      - name: Run tests
        run: bundle exec rspec